# Generated by Django 2.0.2 on 2018-02-04 20:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number should consist of 9 digits.', regex='[0-9]{9}')])),
                ('emailAddress', models.EmailField(max_length=254)),
                ('facebookId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('messageText', models.CharField(max_length=1000)),
                ('actionTaken', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CallCenter.FacebookUser')),
            ],
        ),
    ]
